(define (problem blocks-problem)
  (:domain blocks)
  (:objects blockA blockB blockC blockD - block)
  (:init (big blockA) (small blockB) (big blockC) (big blockD) (ontable blockA) (ontable blockB) (ontable blockC) (ontable blockD) (clear blockA) (clear blockB) (clear blockC) (clear blockD) (handempty))
  (:goal (and (on blockA blockB) (on blockB blockC) (on blockC blockD)))
)